### ISSUE TITLE
交易所错误

### ISSUE THREAD

**Issue by Mjzs12138** [vnpy/vnpy_futu#7]
连接HK_FUTURE接口会出现如下错误：

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/vnpy_futu/futu_gateway.py", line 162, in query_data
    self.query_order()
  File "/opt/homebrew/lib/python3.10/site-packages/vnpy_futu/futu_gateway.py", line 395, in query_order
    self.process_order(data)
  File "/opt/homebrew/lib/python3.10/site-packages/vnpy_futu/futu_gateway.py", line 538, in process_order
    symbol, exchange = convert_symbol_futu2vt(row["code"])
  File "/opt/homebrew/lib/python3.10/site-packages/vnpy_futu/futu_gateway.py", line 586, in convert_symbol_futu2vt
    exchange = EXCHANGE_FUTU2VT[futu_exchange]
KeyError: 'SG'

**Comment by linwaiwai** [comment]
看上去应该交易所映射错误
